#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H
// keywords are NOT,
typedef enum TokenType{ LEFT_PAREN, RIGHT_PAREN, MINUS, PLUS, SLASH, STAR, EQUAL, GREATER,
  GREATER_EQUAL, LESS, LESS_EQUAL, SYMBOL, STRING, NUMBER, AND, NOT, ELSE, FALSE, DEFINE,
  SET, FOR, IF, NIL, OR, TRUE, LAMBDA, DOT, _EOF_} TokenType;
#endif
